# -*- coding: utf-8 -*-
"""Book-Recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14kxO6poqeQ2QLEs_FAjdiFVUOYEr9OcO
"""

# Install required libraries
!pip install -q transformers sentence-transformers pandas numpy scikit-learn

# Import necessary packages
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from transformers import pipeline
import warnings
warnings.filterwarnings('ignore')

# Load the Goodreads dataset (sample)
!wget -q https://raw.githubusercontent.com/zygmuntz/goodbooks-10k/master/books.csv

# Load the dataset
books_df = pd.read_csv('books.csv')

# Select relevant columns and clean data
books_df = books_df[['title', 'authors', 'average_rating', 'language_code', 'ratings_count', 'original_publication_year']]
books_df = books_df.dropna()
books_df = books_df[books_df['language_code'] == 'eng']  # Filter English books

# Add sample descriptions (in a real app, you'd scrape these or use a complete dataset)
sample_descriptions = [
    "A story of love and betrayal set in 1920s New York",
    "A sci-fi adventure about space exploration and alien encounters",
    "A mystery thriller following a detective solving a series of murders",
    "A historical fiction about World War II from multiple perspectives",
    "A self-help book about productivity and time management",
    "A fantasy epic with dragons, magic, and political intrigue",
    "A romance novel about second chances and small-town life",
    "A biography of a famous scientist and their groundbreaking discoveries",
    "A horror story about a haunted house with a dark secret",
    "A business book about startup culture and innovation"
]

books_df['description'] = (sample_descriptions * ((len(books_df) // len(sample_descriptions)) + 1))[:len(books_df)]
books_df = books_df.head(100)  # Limit to 100 books for demo purposes

books_df.head()

# Load sentence transformer model for embeddings
model = SentenceTransformer('all-MiniLM-L6-v2')

# Generate embeddings for book descriptions
book_descriptions = books_df['description'].tolist()
book_embeddings = model.encode(book_descriptions)

def recommend_books(user_preference, n_recommendations=3):
    # Encode user preference
    user_embedding = model.encode([user_preference])

    # Calculate cosine similarity
    similarities = cosine_similarity(user_embedding, book_embeddings)

    # Get top N recommendations
    top_indices = np.argsort(similarities[0])[-n_recommendations:][::-1]
    recommendations = books_df.iloc[top_indices]

    return recommendations

# Test recommendation system
user_input = "I enjoy thrilling mystery novels with complex characters"
recommendations = recommend_books(user_input)
print("Recommended Books:")
print(recommendations[['title', 'authors', 'average_rating']])

# Load summarization pipeline
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

def generate_summary(book_title):
    # Find the book description
    book_desc = books_df[books_df['title'] == book_title]['description'].values[0]

    if len(book_desc.split()) < 20:
        return book_desc

    # Generate summary
    summary = summarizer(book_desc, max_length=100, min_length=30, do_sample=False)

    return summary[0]['summary_text']

# Test summarization
sample_book = recommendations.iloc[0]['title']
print(f"\nSummary for '{sample_book}':")
print(generate_summary(sample_book))

def interactive_book_recommender():
    print("Welcome to the Book Recommendation System!")
    print("Tell us what kind of books you like (e.g., genre, themes, favorite authors):")

    user_input = input("Your preferences: ")

    if not user_input.strip():
        print("Please provide some preferences.")
        return

    print("\nSearching for recommendations...\n")

    try:
        recommendations = recommend_books(user_input, n_recommendations=3)

        print("Here are some books you might enjoy:")
        for idx, row in recommendations.iterrows():
            print(f"\n{row['title']} by {row['authors']} (Rating: {row['average_rating']})")
            summary = generate_summary(row['title'])
            print(f"Summary: {summary}")

    except Exception as e:
        print(f"An error occurred: {e}")

# Run the interactive demo
interactive_book_recommender()