# -*- coding: utf-8 -*-
"""Book Recommender Enhanced.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10tLVOFuG1IQ5c5lMzMH9hwj3gLjj4yIn
"""

import requests
from IPython.display import display, HTML

# Function to query Google Books API and get search results
def search_books(user_description):
    # Google Books API endpoint
    url = "https://www.googleapis.com/books/v1/volumes"

    # Parameters for the search query
    params = {
        "q": user_description,
        "maxResults": 5  # Limit to top 5 results
    }

    # Make a GET request to the API
    response = requests.get(url, params=params)

    # Check if the request was successful
    if response.status_code == 200:
        books = response.json().get("items", [])
        recommended_books = []

        # Parse the book information from the response
        for book in books:
            title = book["volumeInfo"].get("title", "No title available")
            author = book["volumeInfo"].get("authors", ["Unknown author"])[0]
            description = book["volumeInfo"].get("description", "No description available")
            recommended_books.append((title, author, description))

        return recommended_books
    else:
        return []

# Function to display book recommendations
def display_recommendations(user_description):
    # Get recommendations
    recommendations = search_books(user_description)

    # Check if recommendations exist
    if recommendations:
        for title, author, description in recommendations:
            display(HTML(f"<h3>{title}</h3><p><strong>Author:</strong> {author}</p><p>{description}</p><hr>"))
    else:
        display(HTML("<p>No books found based on your description. Try a different one!</p>"))

# Test with a sample user input
user_description = input("Enter a description of the book you're looking for: ")
display_recommendations(user_description)